import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const SatQuestionLayout = ({ testTitle, sections, currentSectionIndex, currentQuestion, currentQuestionIndex, currentSectionQuestions, answers, flags, timer, onSelectQuestion, onAnswer, onToggleFlag, onNext, onPrev, onAutosave, onSubmit, submitting, status, }) => {
    const { minutes, seconds } = timer;
    const formattedTime = `${minutes.toString().padStart(2, '0')}:${seconds
        .toString()
        .padStart(2, '0')}`;
    const answerValue = answers[currentQuestion.id] ?? null;
    const isFlagged = flags[currentQuestion.id] ?? false;
    const section = sections[currentSectionIndex];
    return (_jsxs("div", { className: "sat-shell", children: [_jsxs("header", { className: "sat-topbar", children: [_jsxs("div", { className: "sat-topbar-left", children: [_jsx("div", { className: "sat-logo-pill", children: "SAT" }), _jsxs("div", { className: "sat-topbar-text", children: [_jsx("div", { className: "sat-topbar-title", children: testTitle }), _jsxs("div", { className: "sat-topbar-section", children: [section?.name, " \u00B7 Section ", section?.index + 1] })] })] }), _jsxs("div", { className: "sat-topbar-right", children: [_jsxs("div", { className: "sat-status-indicators", children: [!status.isFullscreen && (_jsx("span", { className: "sat-status-warning", children: "Exit Full Screen" })), !status.isWindowFocused && (_jsx("span", { className: "sat-status-warning", children: "Window not active" })), !status.isDocumentVisible && (_jsx("span", { className: "sat-status-warning", children: "Tab not visible" }))] }), _jsxs("div", { className: "sat-timer-chip", children: [_jsx("span", { className: "sat-timer-label", children: "Time Remaining" }), _jsx("span", { className: "sat-timer-value", children: formattedTime })] }), _jsx("button", { className: `sat-flag-toggle ${isFlagged ? 'sat-flag-on' : ''}`, type: "button", onClick: () => onToggleFlag(currentQuestion.id), children: isFlagged ? 'Clear Flag' : 'Flag for Review' }), _jsx("button", { className: "sat-save-link", type: "button", onClick: () => onAutosave(), children: "Save" }), _jsx("button", { className: "sat-end-test-btn", type: "button", onClick: () => onSubmit(), disabled: submitting, children: submitting ? 'Ending…' : 'End Test' })] })] }), _jsxs("div", { className: "sat-body", children: [_jsxs("aside", { className: "sat-palette", children: [_jsxs("div", { className: "sat-palette-header", children: [_jsx("div", { children: "Question" }), _jsxs("div", { className: "sat-palette-legend", children: [_jsx("span", { className: "sat-legend-dot sat-legend-answered" }), " Answered", _jsx("span", { className: "sat-legend-dot sat-legend-flagged" }), " Flagged", _jsx("span", { className: "sat-legend-dot sat-legend-current" }), " Current"] })] }), _jsx("div", { className: "sat-palette-grid", children: currentSectionQuestions.map((q, index) => {
                                    const answered = !!answers[q.id];
                                    const flagged = flags[q.id];
                                    const isCurrent = index === currentQuestionIndex;
                                    const classes = [
                                        'sat-palette-item',
                                        answered ? 'is-answered' : '',
                                        flagged ? 'is-flagged' : '',
                                        isCurrent ? 'is-current' : '',
                                    ]
                                        .filter(Boolean)
                                        .join(' ');
                                    return (_jsx("button", { type: "button", className: classes, onClick: () => onSelectQuestion(currentSectionIndex, index), children: q.questionNumber }, q.id));
                                }) })] }), _jsxs("main", { className: "sat-main", children: [currentQuestion.passageText && (_jsxs("section", { className: "sat-passage", children: [_jsx("div", { className: "sat-passage-label", children: "Passage" }), _jsx("div", { className: "sat-passage-box", children: currentQuestion.passageText })] })), _jsxs("section", { className: "sat-question-area", children: [_jsxs("div", { className: "sat-question-header", children: [_jsxs("div", { className: "sat-question-number", children: ["Question ", currentQuestion.questionNumber] }), isFlagged && _jsx("div", { className: "sat-flag-indicator", children: "Flagged" })] }), _jsx("div", { className: "sat-question-text", children: currentQuestion.questionText }), currentQuestion.options && currentQuestion.options.length > 0 && (_jsx("div", { className: "sat-options", children: currentQuestion.options.map((opt) => {
                                            const checked = answerValue === opt.value;
                                            return (_jsxs("label", { className: `sat-option-row ${checked ? 'is-selected' : ''}`, children: [_jsx("input", { type: "radio", name: `q-${currentQuestion.id}`, value: opt.value, checked: checked, onChange: () => onAnswer(currentQuestion.id, opt.value) }), _jsx("span", { className: "sat-option-letter", children: opt.label }), _jsx("span", { className: "sat-option-text", children: opt.value })] }, opt.value));
                                        }) })), (!currentQuestion.options ||
                                        currentQuestion.options.length === 0) && (_jsx("div", { className: "sat-gridin", children: _jsxs("label", { className: "sat-gridin-label", children: ["Enter your answer:", _jsx("input", { className: "sat-gridin-input", type: "text", value: answerValue ?? '', onChange: (e) => onAnswer(currentQuestion.id, e.target.value || null) })] }) })), _jsxs("div", { className: "sat-nav-bar", children: [_jsx("button", { type: "button", className: "sat-nav-btn", onClick: onPrev, children: "Previous" }), _jsx("button", { type: "button", className: "sat-nav-btn", onClick: onNext, children: "Next" })] })] })] }), _jsxs("aside", { className: "sat-tools", children: [_jsxs("div", { className: "sat-tools-section", children: [_jsx("div", { className: "sat-tools-header", children: "Calculator" }), _jsx("div", { className: "sat-tools-body", children: "Calculator area" })] }), _jsxs("div", { className: "sat-tools-section", children: [_jsx("div", { className: "sat-tools-header", children: "Reference" }), _jsx("div", { className: "sat-tools-body", children: "Reference sheet" })] })] })] })] }));
};
export default SatQuestionLayout;
